core/urls.py
from django.urls import path, include
from.views import *
from rest_framework import routers
from django.contrib.auth import views as auth_views
from . import views

#Creamos las rutas del api
router = routers.DefaultRouter()
router.register('productos',ProductoViewset)
router.register('tipoproductos',TipoProductoViewset)



urlpatterns = [
    #API
    path('api/', include(router.urls)),
    #RUTAS
    path('Carrito/',Carrito, name="Carrito"),
    path('Contact/',Contact, name="Contact"),
    path('',index, name="index"),
    path('indexapi',indexapi, name="indexapi"),
    path('team/',team, name="team"),

    path('PagarCarrito/', PagarCarrito, name='PagarCarrito'),
    path('pagar/', Pagar, name='pagar'),
    path('AutorizarPago/<int:solicitud_id>/', AutorizarPago, name='AutorizarPago'),
    path('listar_solicitudes_pago/', ListarSolicitudesPago, name='listar_solicitudes_pago'),
    path('completar_compra/<int:solicitud_id>/', CompletarCompra, name='completar_compra'),
    path('autorizacion_exitosa/', pagina_autorizacion_exitosa, name='pagina_autorizacion_exitosa'),
    path('compra_exitosa/', pagina_compra_exitosa, name='pagina_compra_exitosa'),
    path('verificar_autorizacion/<int:solicitud_id>/', verificar_autorizacion, name='verificar_autorizacion'),
    path('rechazar_pago/<int:solicitud_id>/', views.RechazarPago, name='RechazarPago'),


    path('suscripcion/',suscripcion,name='suscripcion'),
    path('suscribirse/',suscribirse,name='suscribirse'),
    path('Finalcompra/',Finalcompra,name='Finalcompra'),
    path('FinalSuscripcion/',FinalSuscripcion,name='FinalSuscripcion'),
    path('suscripcionAdmin/',suscripcionAdmin,name='suscripcionAdmin'),
    path('agregar_al_carrito/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('historial/', historial,name='historial'),
    path('cambiar_estado/<int:pedido_id>/', cambiar_estado_pedido, name='cambiar_estado_pedido'),
    path('seguimiento/', seguimiento, name='seguimiento'),
    path('CambiarGrupo/', CambiarGrupo, name='CambiarGrupo'),
    path('ReporteVentas/', ReporteVentas, name='ReporteVentas'),
    path('perfil/', views.perfil, name='perfil'),


    #Restablecer contraseña
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/uidb64/token/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    #crud
    path('Registrar/',Registrar, name="Registrar"),
    path('add/',add, name="add"),
    path('update/<id>/',update, name="update"),
    path('delete/<id>/',delete, name="delete"),
    path('eliminarCarro/<id>/',eliminarCarro, name="eliminarCarro"),
    path('actualizar_carrito/', actualizar_carrito, name='actualizar_carrito'),
    path('Pagar_suscripcion/', Pagar_suscripcion, name='Pagar_suscripcion'),
    path('addSuscripcion/<id>/', addSuscripcion, name='addSuscripcion'),
    path('deleteSuscripcion/<id>/', deleteSuscripcion, name='deleteSuscripcion'),
    path('updateSuscripcion/<id>/',updateSuscripcion,name='updateSuscripcion'),
    path('salir/', salir, name='salir'),
    

    
    



    

]

pepo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = "PerriPapitos"
admin.site.site_header = "Administracion de la Mascoteria"
admin.site.index_title = "Modulo de Administracion"

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
import random

# Create your models here.

def generar_codigo():
    # Generar un código aleatorio de 10 dígitos
    codigo = ''.join(random.choices('0123456789', k=10))
    return codigo

class TipoProducto(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Producto(models.Model):
    Nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    Stock = models.IntegerField()
    Descripcion = models.CharField(max_length=250)
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    Fecha_creacion = models.DateField()
    imagen = models.ImageField(upload_to='blog-post-image')
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.Nombre

    class Meta:
        db_table = 'db_producto'


class item_carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, default=None)
    items = models.IntegerField(default=0)  # Asegúrate de que este campo esté correctamente definido

    class Meta:
        db_table = 'db_item_carrito'



class Pedido(models.Model):
    ESTADO_CHOICES = (
        ('PENDIENTE', 'Pendiente'),
        ('EN_PROCESO', 'En Proceso'),
        ('ENVIADO', 'Enviado'),
        ('ENTREGADO', 'Entregado'),
        ('CANCELADO', 'Cancelado'),
    )

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    items = models.IntegerField(default=0)
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_compra = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='Pendiente')

    def __str__(self):
        return f"{self.usuario.username} - {self.producto.Nombre}"

    class Meta:
        db_table = 'db_Pedido'


class HistorialCompra(models.Model):
    id = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=10, default=generar_codigo)
    compra = models.ManyToManyField(Pedido)

    def __str__(self):
        return self.codigo

    class Meta:
        db_table = 'db_historial_compra'


class TipoSuscripcion(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()

    def __str__(self):
        return self.nombre

    
class Suscripcion(models.Model):
    usuario  = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, unique=True, related_name='suscripcion')
    suscripcion = models.ForeignKey(TipoSuscripcion, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.username

class SolicitudPago(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2)
    items = models.IntegerField(default=0)  # Campo para almacenar la cantidad de productos
    autorizado = models.BooleanField(default=False)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)
    fecha_autorizacion = models.DateTimeField(null=True, blank=True)
    autorizado_por = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='autorizado_por', null=True, blank=True)
    compra_completada = models.BooleanField(default=False)

    def __str__(self):
        return f"Solicitud de {self.usuario.username}"

core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import * #asi llamamos a todos los models
from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, user_passes_test
from .serializers import *
from rest_framework import viewsets
import requests
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from decimal import Decimal
from django.http import HttpResponse, JsonResponse
from django.db import transaction
from django.db.models import Q
import pandas as pd
from django.utils.dateparse import parse_date
from django.utils import timezone
from functools import wraps

#FUNCION GENERICA QUE VALIDA EL GRUPO DEL USUARIO

def grupo_requerido(*nombres_grupos):
    def check_grupo(user):
        return user.groups.filter(name__in=nombres_grupos).exists()

    def decorator(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if check_grupo(request.user):
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponse("No tienes permiso para acceder a esta página.")
        return wrapper
    return decorator

#@grupo_requerido('vendedor')
# CUANDO CREAN EN USUARIO LO ASIGNA INMEDIATAMENTE AL GRUPO
# grupo = Group.objects.get(name='usuario')
# user.groups.add(grupo)

#NOS PERMITE MOSTRAR LA INFO
class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    #queryset = Producto.objects.filter(tipo=1)
    serializer_class = ProductoSerializer

class TipoProductoViewset(viewsets.ModelViewSet):
    queryset = TipoProducto.objects.all()
    #queryset = Producto.objects.filter(tipo=1)
    serializer_class = TipoProductoSerializer

def index(request):

    productosAll = Producto.objects.all()

 
    query = request.GET.get('q')
    if query:
        productosAll = productosAll.filter(
            Q(Nombre__icontains=query) | Q(Descripcion__icontains=query)
        )

  
    page = request.GET.get('page', 1) 

    
    try:
        paginator = Paginator(productosAll, 12)
        productosAll = paginator.page(page)
    except:
        raise Http404

    data = {
        'listado': productosAll,
        'paginator': paginator
    }

    if request.method == 'POST':
        # Procesa la solicitud POST para agregar elementos al carrito, asumiendo que hay un modelo item_carrito definido
        Carrito = item_carrito()
        Carrito.Nombre = request.POST.get('nombre_producto')
        Carrito.precio = request.POST.get('precio_producto')
        Carrito.imagen = request.POST.get('imagen_producto')
        Carrito.save()
        
    return render(request, 'core/index.html', data)


@grupo_requerido('vendedor')
def CambiarGrupo(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        group_name = request.POST.get('group_name')
        try:
            user = User.objects.get(id=user_id)
            group = Group.objects.get(name=group_name)
            user.groups.clear()
            user.groups.add(group)
        except User.DoesNotExist:
            pass
        except Group.DoesNotExist:
            pass
        return redirect('CambiarGrupo')

    users = User.objects.all()
    groups = Group.objects.all()

    data = {
        'users': users,
        'groups': groups,
    }

    return render(request, 'core/CambiarGrupo.html', data)

@grupo_requerido('vendedor')
def indexapi(request):
    #OBTIENE LOS DATOS DEL API
    respuesta = requests.get('http://127.0.0.1:8000/api/productos/')
    respuesta2 = requests.get('https://mindicador.cl/api')
    respuesta3 = requests.get('https://rickandmortyapi.com/api/character')
    #TRANSFORMAR EL JSON
    productos = respuesta.json()
    monedas = respuesta2.json()
    aux = respuesta3.json()
    personajes = aux['results']

    data = {
        'listado': productos,
        'monedas': monedas,
        'personajes':personajes,
    }

   
    return render(request,'core/indexapi.html', data)  


    

#CRUD

def Registrar(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method =='POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            grupo = Group.objects.get(name='cliente')
            user.groups.add(grupo)
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to="index")
        data["form"] = formulario

    return render(request, 'registration/Registrar.html', data)

def salir (request):
    logout(request)
    messages.success(request,F"Tu sesion se ha cerrado")
    return redirect(to="index")

@grupo_requerido('vendedor','bodeguero')
def add(request):
    data = {
        'form': ProductoForm(initial={'Fecha_creacion': timezone.now()})  # Establece la fecha actual como valor inicial
    }
    if request.method == 'POST':
        formulario = ProductoForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto almacenado correctamente")

    return render(request, 'core/add-product.html', data)




@grupo_requerido('vendedor','bodeguero')
def update(request, id):
    producto = get_object_or_404(Producto, id=id)  # Obtener un producto por su ID

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            messages.success(request, "Producto actualizado correctamente")
            return redirect('index')
    else:
        form = ProductoForm(instance=producto)

    data = {
        'form': form,
    }

    return render(request, 'core/add-product.html', data)

@login_required
def delete(request,id):
    producto = Producto.objects.get(id=id) #OBTIENE UN PRODUCTO POR EL ID
    producto.delete()

    return redirect(to='index')



@login_required
def agregar_al_carrito(request, producto_id):
    # Obtener el usuario actualmente autenticado
    usuario = request.user
    
    # Obtener el producto utilizando su ID
    producto = Producto.objects.get(id=producto_id)
    
    # Verificar si el producto ya está en el carrito del usuario
    carrito_existente = item_carrito.objects.filter(usuario=usuario, producto=producto).first()
    
    if carrito_existente:
        # Si el producto ya está en el carrito, se incrementa la cantidad
        carrito_existente.items += 1
        carrito_existente.save()
    else:
        # Si el producto no está en el carrito, se crea un nuevo registro
        nuevo_item = item_carrito(usuario=usuario, producto=producto, items=1)
        nuevo_item.save()
    # Actualizar el stock del producto
    producto.Stock -= 1
    producto.save()
    
    # Retornar un mensaje de éxito
    return redirect(request.META['HTTP_REFERER'])



@login_required
def actualizar_carrito(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        cantidad = int(request.POST.get('cantidad'))
        
        # Actualizar la cantidad del producto en el carrito
        try:
            item = item_carrito.objects.get(id=item_id)
            producto = item.producto
            stock_actual =int(producto.Stock)
            if cantidad > stock_actual:
                messages.error(request, 'No hay suficiente stock disponible.')
            else:
                # Calcular la diferencia de stock
                diferencia_stock = cantidad - item.items
                item.items = cantidad
                item.save()
                producto.Stock = stock_actual - diferencia_stock
                producto.save()


            messages.success(request, 'El carrito se ha actualizado correctamente.')
        except item_carrito.DoesNotExist:
            messages.error(request, 'El producto no existe en el carrito.')
        
        return redirect(request.META['HTTP_REFERER'])

    return redirect('core/Carrito.html') 

@login_required
def Carrito(request):
    # Obtener los productos en el carrito del usuario actual
    items = item_carrito.objects.filter(usuario=request.user)

    # Obtener el valor del dólar desde la API de Mindicador
    respuesta = requests.get('https://mindicador.cl/api/dolar').json()
    valor_usd = respuesta['serie'][0]['valor']

    # Calcular el precio total de cada producto en CLP y USD
    for item in items:
        item.precio_total = item.items * item.producto.precio
        item.precio_total_usd = item.precio_total / valor_usd

    # Calcular el precio total del carrito en CLP y USD
    precio_total = sum(item.precio_total for item in items)
    precio_total_usd = round(sum(item.precio_total_usd for item in items), 2)

    # Pasar los productos, precios totales en CLP y USD al template como parte del contexto
    data = {
        'items': items,
        'precio_total': precio_total,
        'precio_total_usd': precio_total_usd,
        # Otros datos que ya tienes en tu vista...
    }

    return render(request, 'core/Carrito.html', data)

@login_required
def eliminarCarro(request, id):
    carrito = item_carrito.objects.get(id=id)
    
    # Obtener el producto del carrito
    producto = carrito.producto
    
    # Incrementar el stock del producto
    producto.Stock += carrito.items
    producto.save()
    
    # Eliminar el registro del carrito
    carrito.delete()
    
    return redirect("Carrito")


def Contact(request):
    return render(request,'core/Contact.html')
    



def team(request):
    productosAll = Producto.objects.all()#SELECT * FROM producto

core/templates/core/AutorizarPago.html
{% extends 'core/base.html' %}
{% load static %}
{% block nav %}
<a href="{% url 'index' %}" class="nav-item nav-link ">Inicio</a>
{% for group in user.groups.all %}
{% if group.name == 'vendedor' %}
<a href="{% url 'add' %}" class="nav-item nav-link">Administracion</a>
<a href="{% url 'listar_solicitudes_pago' %}" class="nav-item nav-link">Solicitudes</a>
{% endif %}
{% endfor %}
{% if user.is_authenticated %}
<a href="{% url 'Carrito' %}" class=" nav-item nav-link active"><i class="fa fa-shopping-cart "></i></a>
{% else %}
<a onclick="NoIniciado()" class=" nav-item nav-link"><i class="fa fa-shopping-cart "></i></a>
{% endif %}
{% endblock %}

{% block contenido %}

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Autorizar Pago</h1>
    </div>
</div>

<div class="container my-5">
    <div class="card">
        <div class="card-body text-center">
            <h2 style="color: #1995AD;">Autorizar</h2>

            <h1 style="color: #1995AD;">Usuario: {{ solicitud.usuario.username }}</h1>
            <h1 style="color: #1995AD;">Precio Total: {{ solicitud.precio_total }}</h1>
            <h1 style="color: #1995AD;">Valor Total en USD: {{ solicitud.valor_total }}</h1>


            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Autorizar</button>
                <a href="{% url 'listar_solicitudes_pago' %}" class="btn btn-primary">Cancelar</a>
            </form>

        </div>
    </div>
</div>
{% endblock %}

core/templates/core/CambiarGrupo.html
{% extends 'core/base.html' %}
{% load static %}
{% block nav %}
<a href="{% url 'index' %}" class="nav-item nav-link ">Inicio</a>
{% for group in user.groups.all %}
        {% if group.name == 'cliente' %}
<a href="{% url 'historial' %}" class="nav-item nav-link">Historial de compra</a>
        {% endif %}
    {% endfor %}
{% for group in user.groups.all %}
    {% if group.name == 'vendedor' %}
<a href="{% url 'add' %}" class="nav-item nav-link">Administracion</a>
    {% endif %}
{% endfor %}
{% if user.is_authenticated %}
<a href="{% url 'Carrito' %}" class=" nav-item nav-link active"><i class="fa fa-shopping-cart "></i></a>
{% else %}
<a onclick="NoIniciado()" class=" nav-item nav-link"><i class="fa fa-shopping-cart "></i></a>
{% endif %}
{% endblock %}

{% block contenido %}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Cambiar Grupo</h1>
    </div>
</div>



<div class="d-flex justify-content-center align-items-center" style="height: 300px;">
    <div class="container" style="max-width: 500px;">
        <h3 class="text-center">Usuarios</h3>
        <form method="POST" action="{% url 'CambiarGrupo' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="user_id">Usuario</label>
                <select name="user_id" id="user_id" class="form-control">
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <h3 style="margin-top: 50px;" class="text-center">Grupos</h3>
                <label for="group_name">Nuevo Grupo</label>
                <select name="group_name" id="group_name" class="form-control">
                    {% for group in groups %}
                        <option value="{{ group.name }}">{{ group.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary mt-3 w-100">Cambiar Grupo</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/Finalcompra.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
<div class="payment-total">
    <h2>!!!COMPRA FINALIZADA¡¡¡</h2>
    <div class="d-flex justify-content-center">
    <i style="font-size: 150px; color: rgb(255, 162, 0);" class="fas fa-thumbs-up"></i>
    </div>
    <p></p>
    <p></p>

    <h3>
        Gracias por tu compra, se enviara un correo con todos los datos de envio
    </h3>

    <form method="POST" action="{% url 'Carrito' %}">
        {% csrf_token %}


        <a href="{% url 'index' %}" class="btn btn-primary"> Finalizar compra</a>
    </form>
</div>
{% endblock %}

core/templates/core/PaginaCompraExitosa.html
<!DOCTYPE html>
<html>
<head>
    <title>Compra Exitosa</title>
</head>
<body>
    <h1>La compra se ha completado exitosamente.</h1>
</body>
</html>

core/templates/core/add-product.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block nav %}
<!-- Tu código de navegación aquí -->
{% endblock %}

{% block contenido %}

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Administracion</h1>
    </div>
</div>
<h3>Agregar Producto</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-3">Guardar</button>
</form>

{% endblock %}

{% block js %}
{% endblock %}

core/templates/core/seguimiento.html
{% extends 'core/base.html' %}
{% load static %}
{% block nav %}
<a href="{% url 'index' %}" class="nav-item nav-link ">Inicio</a>
<a href="{% url 'team' %}" class="nav-item nav-link ">Productos</a>
{% for group in user.groups.all %}
    {% if group.name == 'cliente' %}
<a href="{% url 'historial' %}" class="nav-item nav-link">Historial de compra</a>
    {% endif %}
{% endfor %}
{% for group in user.groups.all %}
    {% if group.name == 'vendedor' %}
<a href="{% url 'add' %}" class="nav-item nav-link active">Administracion</a>
    {% endif %}
{% endfor %}
{% if user.is_authenticated %}
<a href="{% url 'Carrito' %}" class=" nav-item nav-link"><i class="fa fa-shopping-cart "></i></a>
{% else %}
<a onclick="NoIniciado()" class=" nav-item nav-link"><i class="fa fa-shopping-cart "></i></a>
{% endif %}
{% endblock %}


{% block contenido %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Seguimiento de pedido</h1>
    </div>
  </div>

{% if user.is_authenticated or user.username == 'bodeguero' %}
<hr class="my-4">
<section class="h-135 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-10 col-xl-8">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-4">
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <p class="lead fw-normal mb-0" >Pedidos</p>
                        </div>
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="filtroUsuarioDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Filtrar por usuario
                            </button>
                            <div class="dropdown-menu" aria-labelledby="filtroUsuarioDropdown">
                                <a class="dropdown-item {% if not nombre_usuario %}active{% endif %}" href="{% url 'seguimiento' %}">Todos</a>
                                {% for usuario in usuarios %}
                                    <a class="dropdown-item {% if nombre_usuario == usuario.username %}active{% endif %}" href="?usuario={{ usuario.username }}">{{ usuario.username }}</a>
                                {% endfor %}
                            </div>
                        </div>
                        {% for pedido in pedidos %}
                            <div class="card shadow-0 border mb-4">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <p>Usuario: {{ pedido.usuario.username }}</p>
                                        </div>
                                        <div class="col-md-2">
                                            <p>Código de compra: {{ pedido.historialcompra_set.first.codigo }}</p>
                                        </div>
                                        <div class="col-md-2">
                                            <p>Productos:</p>
                                            <p> {{ pedido.producto.Nombre }}</p>
                                        </div>
                                        <div class="col-md-2">
                                            <p>Comprador: {{ pedido.usuario.username }}</p>
                                        </div>
                                        <div class="col-md-2">
                                            <p>Estado: {{ pedido.estado }}</p>
                                        </div>
                                        <div class="col-md-2">
                                            <form method="POST" action="{% url 'cambiar_estado_pedido' pedido.pk %}">
                                                {% csrf_token %}
                                                <label for="nuevo_estado">Estado:</label>
                                                <select name="nuevo_estado" id="nuevo_estado">
                                                    <option value="validacion" {% if pedido.estado == 'validacion' %}selected{% endif %}>Validación</option>
                                                    <option value="preparacion" {% if pedido.estado == 'preparacion' %}selected{% endif %}>Preparación</option>
                                                    <option value="reparto" {% if pedido.estado == 'reparto' %}selected{% endif %}>Reparto</option>
                                                    <option value="entregado" {% if pedido.estado == 'entregado' %}selected{% endif %}>Entregado</option>
                                                    <option value="cancelado" {% if pedido.estado == 'cancelado' %}selected{% endif %}>Cancelado</option>
                                                </select>
                                                <br>
                                                <input type="submit" value="Guardar" class="btn btn-primary mt-3">
                                            </form>
                                        </div>
                                    </div>
                                    <hr class="mb-4" style="background-color: #ff8400; opacity: 1;">
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}

{% endblock %}